secrets:
  esp:
    azure-logaccess: "azure-logaccess"
vaults:
  esp:
  - name: my-azure-logaccess-vault
    url: http://${env.VAULT_SERVICE_HOST}:${env.VAULT_SERVICE_PORT}/v1/secret/data/esp/${secret}
    kind: kv-v2
